### ISSUE TITLE
Random failure of users list length

### ISSUE THREAD

**Issue by travi** [travi/travi-api#113]
seems to be related to the fact that a list of length one is collapsed to not be a list

**Comment by travi** [comment]
```
{ _links: { self: { href: 'http://example.com/users/RqJzJabk' } },
  id: 'RqJzJabk',
  'first-name': 'dU31hbHP',
  'last-name': 'CT00TERK',
  email: 'Ttdl1xiD@0XDT8raGgnDeIq3qFx6k.yH1',
  avatar: 
   { src: 'https://www.gravatar.com/avatar/b8dfba1fa2f6bf366f5b090fa7725bf3?size=32',
     size: 32 } }
    Then a list of "users" is returned                  # test/integration/features/step_definitions/resources.js:117
      AssertionError: [assert.equals] undefined expected to be equal to 1
          at referee.fail (/home/travis/build/travi/travi-api/node_modules/referee/lib/referee.js:193:25)
          at Object.ctx.fail (/home/travis/build/travi/travi-api/node_modules/referee/lib/referee.js:90:21)
          at assertion (/home/travis/build/travi/travi-api/node_modules/referee/lib/referee.js:98:21)
          at Function.referee.(anonymous function).(anonymous function) [as equals] (/home/travis/build/travi/travi-api/node_modules/referee/lib/referee.js:118:23)
          at World.<anonymous> (/home/travis/build/travi/travi-api/test/integration/features/step_definitions/resources.js:125:16)
          at nextTickCallbackWith0Args (node.js:452:9)
```
